[package]
name = "tokenize"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2"  # MIT
vibrato = { path = "../vibrato" }
clap = { version = "4.0", features = ["derive"] }  # MIT or Apache-2.0
zstd = "0.12"  # MIT
