[package]
name = "dictgen"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.0-rc.1"  # MIT
clap = { version = "3.2.22", features = ["derive"] }  # MIT or Apache-2.0
ruzstd = "0.3.0"  # MIT
vibrato = { path = "../vibrato" }
