[package]
name = "dictgen"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"

[dependencies]
clap = { version = "4.0", features = ["derive"] }  # MIT or Apache-2.0
ruzstd = "0.3.0"  # MIT
vibrato = { path = "../vibrato" }
